---
  title: "Chapter 5: Framing Unification"
  subtitle: "Online Appendix"
---

```{r setup, include=FALSE}
setwd("~/Public/klarahan.github.io")
#Sys.setlocale(locale = "Korean")
```

Load libraries
```{r message=FALSE, warning=FALSE}
library(lubridate)
library(ggplot2)
library(dplyr)
library(tidytext)
library(quanteda)
library(scales)
library(LSX)

```

Load the data.
```{r}
data_uni <- readRDS("data/data_uni_nouns_sample")
```

#Scaling
Load the Korean sentiment lexicon.
```{r emo, echo=FALSE}
# sentiment lexicon source:
# https://sites.google.com/site/datascienceslab/projects/multilingualsentiment
pos <- readr::read_delim("data/positive_words_ko.txt", delim='\t', col_names=c("term")) %>% 
  rename(word = term) %>% 
  tibble::add_column(sentiment = "positive")
neg <- readr::read_delim("data/negative_words_ko.txt", delim='\t', col_names=c("term")) %>% 
  rename(word = term) %>% 
  tibble::add_column(sentiment = "negative")
senti <- bind_rows(pos, neg) 
senti
```

See the top sentiment words.
```{r}
tidy_news <- data_uni %>% 
  unnest_tokens(word, text)

tidy_news %>%
  inner_join(senti) %>%
  count(word, sort = TRUE) 

senti_news <- tidy_news %>%
  inner_join(senti) %>%
  count(Newspaper, Prezparty, sentiment) %>%
  tidyr::spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)

senti_word_counts <- tidy_news %>%
  inner_join(senti) %>%   
  filter(Government == "1990-1993 Roh TW") %>% 
  count(word, sentiment, Government, sort = TRUE) %>%
  ungroup()

senti_word_counts
```

Plot the top sentiment words.
```{r message=TRUE, warning=TRUE}
senti_word_counts %>%
  group_by(sentiment) %>%
  top_n(25) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "Contribution to sentiment",
       x = NULL) +
  coord_flip() +
  scale_fill_grey() +
  theme_bw()
```

```{r}
# Sys.setlocale(locale = "C")
dict_sentiment <- dictionary(list(positive = c("구상", "자유", "평화", "협력", "지원", "번영"),
                                 negative = c("투쟁", "대립", "무산", "세력", "비판", "분열")))
dict_sentiment
```


```{r}

# tokenize text corpus and remove various features
corp_sent <- data_uni %>% 
  unique() %>% 
  mutate(Body = gsub("</?[^>]+>|▲ 종이신문보기", "", Body)) %>% 
  corpus() %>% 
  corpus_reshape(to =  "sentences")
toks <- corp_sent %>% 
    tokens()

# create a document feature matrix from the tokens object
dfmat <- toks %>% 
    dfm(remove = "") %>% 
    dfm_trim(min_termfreq = 5)
```

```{r}
topfeatures(dfmat, 20)

```

```{r}
seed <- as.seedwords(dict_sentiment)
seed
```

```{r}
# identify context words 
context_terms <- char_context(toks, pattern = "*통일*", p = 0.05)

# run LSS model
tmod_lss <- textmodel_lss(dfmat, seeds = seed,
                          terms = context_terms, k = 300, cache = TRUE)
```
Look up key periods
```{r}
#Sys.setlocale(locale = "Korean")

data_uni %>% 
  filter(grepl("회장", text)) %>% 
  select(Body)
```

```{r}
head(coef(tmod_lss), 20) # most positive words

```

```{r}
tail(coef(tmod_lss), 20) # most negative words

```

```{r}
textplot_terms(tmod_lss, dict_sentiment[c("negative", "positive")])
# ggsave("plots/5_uni_seeds.jpg", width=8, height= 5, dpi = 300)

```

```{r}
dfmat <- dfm_group(dfmat)
# predict sentiment scores
pred <- as.data.frame(predict(tmod_lss, se.fit = TRUE, newdata = dfmat))
pred$date <- docvars(dfmat, "Date")
pred$Newspaper <- docvars(dfmat, "Newspaper")

```

```{r}
plot(pred$date, pred$fit, col = rgb(0, 0, 0, 0.05), 
     pch = 20, ylim = c(-1, 1),
     ylab = "Threat Intensity")
```


```{r}
pred_sm_chos <- pred %>% 
  filter(Newspaper == "Chosun") %>% 
  smooth_lss(engine = "locfit")
pred_sm_hani <- pred %>% 
  filter(Newspaper == "Hankyoreh") %>% 
  smooth_lss(engine = "locfit")
pred_sm_hankook <- pred %>% 
  filter(Newspaper == "Hankook") %>% 
  smooth_lss(engine = "locfit")

# Sys.setlocale(locale = "Korean")
head(pred_sm_chos)
head(pred_sm_hani)
head(pred_sm_hankook)

```

plot trend 
```{r}
x <- bind_rows("Chosun" = pred_sm_chos, "Hankyoreh" = pred_sm_hani, .id = "Newspaper") %>% 
  mutate(date = as.Date(date, format = "ymd")) %>% 
  mutate(Newspaper = as.factor(Newspaper)) %>% 
  ggplot(aes(date, fit, group = Newspaper, color = Newspaper, fill = Newspaper)) +
  annotate("rect", xmin = as.Date("1998-02-25"), xmax = as.Date("2008-02-2"), 
           ymin = -Inf, ymax = Inf, alpha = 0.2) +
  geom_line() +
  geom_ribbon(aes(ymin = fit + se.fit, ymax = fit - se.fit), alpha = 0.3) +
  geom_hline(yintercept = 0) +
  scale_color_manual(values = c("grey20", "grey70")) +
  theme_bw() +
  labs(x = "Year", y = "Negative vs. Positive",
       caption = "1. First Inter-Korean Summit between North and South Korea (Kim DJ)\n2. National Assembly votes for dismissal of Unification Minister in Pres. Kim's Sunshine Policy\n3. North Korea test-fires seven long-, mid-, and short-range ballistic missiles\n4. Second Inter-Korean Summit between North and South Korea (Roh MH)\n5. Sinking of the Cheonan military vessel")  +
  scale_x_date(breaks = "1 year", labels = date_format("%Y"), 
           limits = as.Date(c("1990-01-01", "2014-12-31")), expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "top")  +
  scale_fill_manual(values=c("grey20", "grey70")) +
  annotate(geom = "text", x = as.Date("1994-01-01"), y = 0.5, 
           label = "Conservative\ngovernments", hjust = "center") +
  annotate(geom = "text", x = as.Date("2003-01-01"), y = 0.5, 
           label = "Liberal\ngovernments", hjust = "center") +
  annotate(geom = "text", x = as.Date("2012-01-01"), y = 0.5, 
         label = "Conservative\ngovernments", hjust = "center") +
  annotate(geom = "text", x = as.Date("2000-06-13"), y = 0.37, 
         label = "1", hjust = "center", size = 4) +
  annotate(geom = "text", x = as.Date("2001-9-3"), y = 0.37, 
       label = "2", hjust = "center", size = 4) +
  annotate(geom = "text", x = as.Date("2006-07-4"), y = 0.37, 
       label = "3", hjust = "center", size = 4) +
  annotate(geom = "text", x = as.Date("2007-10-02"), y = 0.37, 
         label = "4", hjust = "center", size = 4) +
  annotate(geom = "text", x = as.Date("2010-3-26"), y = 0.37, 
         label = "5", hjust = "center", size = 4) +
  annotate("segment", x = as.Date(c("2000-06-13", "2001-9-3", "2006-07-4", "2007-10-02", "2010-3-26")),
           xend = as.Date(c("2000-06-13", "2001-9-3", "2006-07-4", "2007-10-02", "2010-3-26")), 
           y = - Inf, yend = 0.33, linetype = 3) +
  ylim(-0.45, 0.55) 


x
# ggsave("plots/5_uni_lss.jpg", width=9, height= 5, dpi = 300)

```
Look up key periods
```{r}
data_uni %>% 
  filter(Date > "2001-9-01" & Date < "2001-09-30") %>%
  mutate(Body = gsub("</?[^>]+>|▲ 종이신문보기", "", Body)) 
```

read news
```{r}
# Sys.setlocale(locale = "Korean")
x <- data_uni %>% 
  filter(Newspaper == "Chosun"  & Date < "2002-01-01" & Date > "2001-01-01" ) %>%
  mutate(Body = gsub("</?[^>]+>|▲ 종이신문보기", "", Body)) %>% 
  filter(grepl("김정일", text)) %>% 
  select(Date, Title, Body, Newspaper)
x
x[4,] %>% write.csv()
```
 
 
# Keyness
Load the data.
```{r}
data_uni <- readRDS("data/toks_uni")
```

Prepare and check
```{r}
# Sys.setlocale(locale = "C")

stopwords <- c("그래픽", "지난해", "한겨레", "기사", "기자", "본지", "측은", "작년", "신문", "종이", "우리", "지면", "보도", "생각", "이날", "간의", "조선일보", "블로그", "일자", "지음", "발인", "병원", "부친상", "모친상", "천억", "천만", "애초", "이용인", "이제훈", "김인구", "에스", "일동", "상사", "약수", "조처", "조치", "과장", "팀장", "원제", "본부", "회장", "임직원", "이사", "당초", "텔레비전", "의원", "후보",
"입장", "총재", "대통령", "김정", "관계자", "소식통", "원장", "학회", "장인상", "김민배", "선생", "경영")
# stopwords_wild <- c("경제민주화*")

#KIm DJ
data_words <- data_uni %>% 
  tokens_subset(!docvars(data_uni, "Newspaper") == "Hankook" &  
                docvars(data_uni, "Government") == "1998-2003 Kim DJ") %>% 
  tokens_remove(pattern = stopwords, valuetype = "fixed") %>%
  # tokens_remove(pattern = stopwords_wild, valuetype = "glob") %>% 
  dfm()

# Sys.setlocale(locale = "Korean")
tstat_freq <- data_words %>% 
  dfm() %>% 
  textstat_frequency(n = 20)
head(tstat_freq, 40)

#text scaling
result_keyness <- textstat_keyness(data_words, target = docvars(data_words, "Newspaper") == "Chosun") 
textplot_keyness(result_keyness, n = 10, color = c("grey20", "grey80")) 

#different period
data_words2 <- data_uni %>% 
  tokens_subset(!docvars(data_uni, "Newspaper") == "Hankook" &  
                docvars(data_uni, "Government") == "2008-2013 Lee MB") %>% 
  tokens_remove(pattern = stopwords, valuetype = "fixed") %>%
  # tokens_remove(pattern = stopwords_wild, valuetype = "glob") %>% 
  dfm()

# Sys.setlocale(locale = "Korean")
tstat_freq <- data_words %>% 
  dfm() %>% 
  textstat_frequency(n = 20)
head(tstat_freq, 40)

#text scaling
result_keyness2 <- textstat_keyness(data_words2, target = docvars(data_words2, "Newspaper") == "Chosun") 
textplot_keyness(result_keyness2, n = 10, color = c("grey20", "grey80")) 


```
Look up stray words
```{r}
# Sys.setlocale(locale = "C")
x <- data_uni %>% 
  # tokens_subset(docvars(data_uni, "Newspaper") == "Hankyoreh") %>% 
  kwic(pattern = "자민련Korean")
x
```

Plot and label
```{r#  message=FALSE, warning=FALSE}
x <- textplot_keyness(result_keyness, n = 10) +
  xlim(-3500, 2500) +
  labs(color = "Newspaper", subtitle = "1998-2003 Kim DJ government (liberal/progressive)",
       caption = "x-axis: chi-squared test for significance of observed versus expected frequency") +
  scale_color_manual(values = c("black", "grey80"), 
                     labels = c("Chosun Ilbo", "Hankyoreh")) +
  annotate("text", x = -20, y = 20, label = "North Korean side", hjust = 1) +
  annotate("text", x = -20, y = 19, label = "South Korean side", hjust = 1) +
  annotate("text", x = -20, y = 18, label = "mainstream", hjust = 1) +
  annotate("text", x = -20, y = 17, label = "Kim Jong-il", hjust = 1) +
  annotate("text", x = -20, y = 16, label = "North Korea", hjust = 1) +
  annotate("text", x = -20, y = 15, label = "United Liberal Democrats", hjust = 1) +
  annotate("text", x = -20, y = 14, label = "Republic of Korea", hjust = 1) +
  annotate("text", x = -20, y = 13, label = "Peking", hjust = 1) +
  annotate("text", x = -20, y = 12, label = "Samsung", hjust = 1) +
  annotate("text", x = -20, y = 11, label = "bilateral", hjust = 1) +
  annotate("text", x = 20, y = 10, label = "Korean peninsula", hjust = 0) +
  annotate("text", x = 20, y = 9, label = "bilateral", hjust = 0)  +
  annotate("text", x = 20, y = 8, label = "Minjok ('Korean nation')", hjust = 0) +
  annotate("text", x = 20, y = 7, label = "peace", hjust = 0) +
  annotate("text", x = 20, y = 6, label = "unarmed", hjust = 0) +
  annotate("text", x = 20, y = 5, label = "fellow countrymen", hjust = 0) +
  annotate("text", x = 20, y = 4, label = "pretext", hjust = 0) +
  annotate("text", x = 20, y = 3, label = "South-North", hjust = 0)+
  annotate("text", x = 20, y = 2, label = "Southern side", hjust = 0) +
  annotate("text", x = 20, y = 1, label = "Northern side", hjust = 0)

x
# ggsave("plots/5_uni_keyness.jpg", width=7, height=4, dpi = 300)

```

```{r message=FALSE, warning=FALSE}
x <- textplot_keyness(result_keyness2, n = 10) +
  xlim(-3500, 2500) +
  labs(color = "Newspaper", subtitle = "2008-2013 Lee MB government (conservative)",
       caption = "x-axis: chi-squared test for significance of observed versus expected frequency") +
  scale_color_manual(values = c("black", "grey80"), 
                     labels = c("Chosun Ilbo", "Hankyoreh")) +
  annotate("text", x = -30, y = 20, label = "North Korea", hjust = 1) +
  annotate("text", x = -30, y = 19, label = "Kim Jong-il", hjust = 1) +
  annotate("text", x = -30, y = 18, label = "North Korean side", hjust = 1) +
  annotate("text", x = -30, y = 17, label = "Republic of Korea", hjust = 1) +
  annotate("text", x = -30, y = 16, label = "North Korean defector", hjust = 1) +
  annotate("text", x = -30, y = 15, label = "China", hjust = 1) +
  annotate("text", x = -30, y = 14, label = "Kim Jong-un", hjust = 1) +
  annotate("text", x = -30, y = 13, label = "industrialized", hjust = 1) +
  annotate("text", x = -30, y = 12, label = "host", hjust = 1) +
  annotate("text", x = -30, y = 11, label = "provocation", hjust = 1) +
  annotate("text", x = 30, y = 10, label = "relations", hjust = 0) +
  annotate("text", x = 30, y = 9, label = "democracy", hjust = 0)  +
  annotate("text", x = 30, y = 8, label = "Yushin (Park Chung-hee)", hjust = 0) +
  annotate("text", x = 30, y = 7, label = "society", hjust = 0) +
  annotate("text", x = 30, y = 6, label = "South and North", hjust = 0) +
  annotate("text", x = 30, y = 5, label = "Park Chung-hee", hjust = 0) +
  annotate("text", x = 30, y = 4, label = "proclamation", hjust = 0) +
  annotate("text", x = 30, y = 3, label = "plan", hjust = 0)+
  annotate("text", x = 30, y = 2, label = "Southern side", hjust = 0) +
  annotate("text", x = 30, y = 1, label = "Northern side", hjust = 0)

x
# ggsave("plots/5_uni_keyness_Lee.jpg", width=7, height=4, dpi = 300)

```

